version: '3.1'

services:
  mariadb_csv:
    image: mariadb:10.3
    container_name: mariadb_csv
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: upload_csv

  phpmyadmin_csv:
    image: phpmyadmin
    container_name: phpmyadmin_csv
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb_csv

  upload-csv:
    image: 'upload-csv:latest'
    container_name: upload-csv
    restart: always
    build:
      context: upload-csv
      dockerfile: Dockerfile

    depends_on:
      - mariadb_csv
      - phpmyadmin_csv
      - ftp
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb_csv:3306/upload_csv?useSSL=false

  ftp:
     build:
       context: docker-ftp-server
       dockerfile: Dockerfile
     container_name: ftp-server
     volumes:
       - db-data:/ftp-home
     environment:
       FTP_USER: test
       FTP_PASS: 1234
volumes:
  db-data:

#  ftpd_server:
#    image: stilliard/pure-ftpd
#    container_name: ftpd_server
##    network_mode: host
#    ports:
#      - "21:21"
#      - "30000-30009:30000-30009"
#    volumes:
#      - "c:/ftp/data:/home/username/"
#      - "c:/ftp/passwd:/etc/pure-ftpd/passwd"
#    environment:
#      PUBLICHOST: "localhost"
#      FTP_USER_NAME: abc
#      FTP_USER_PASS: 1234
#      FTP_USER_HOME: /
#    restart: always

